version: 2

sources:
  - name: raw_data       # must match first argument in source()
    database: taxi_rides_ny
    schema: prod   
    tables:
      - name: yellow_tripdata # must match second argument exactly
      - name: green_tripdata
      - name: fhv_tripdata


    

